"""CLI commands for setup and configuration."""

from __future__ import annotations

from pathlib import Path
import subprocess

from rich.console import Console
import typer

console = Console()

CONFIG_DIR = Path.home() / ".config" / "hellmholtz"
CONFIG_FILE = CONFIG_DIR / ".env"

app = typer.Typer(help="Setup and configuration commands")


def get_config_value(key: str) -> str | None:
    """Get a value from the existing config file."""
    if CONFIG_FILE.exists():
        for line in CONFIG_FILE.read_text().splitlines():
            if line.startswith(f"{key}="):
                value = line.split("=", 1)[1]
                return value.strip('"').strip()
    return None


def write_config(api_key: str | None, base_url: str | None, default_models: str | None) -> None:
    """Write configuration to .env file."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # Generate new config
    date_str = subprocess.check_output(["date"], text=True).strip()
    lines = [
        "# Helmholtz Blablador Configuration (user-level)\n",
        f"# Generated by hellm setup on {date_str}\n",
        "\n",
    ]

    # Write API key
    if api_key:
        lines.append(f'BLABLADOR_API_KEY="{api_key}"\n')
    elif get_config_value("BLABLADOR_API_KEY"):
        lines.append(f'BLABLADOR_API_KEY="{get_config_value("BLABLADOR_API_KEY")}"\n')
    else:
        lines.append("# BLABLADOR_API_KEY=your-api-key-here\n")

    # Write base URL
    if base_url:
        lines.append(f'BLABLADOR_API_BASE="{base_url}"\n')
    elif get_config_value("BLABLADOR_API_BASE"):
        lines.append(f'BLABLADOR_API_BASE="{get_config_value("BLABLADOR_API_BASE")}"\n')
    else:
        lines.append("# BLABLADOR_API_BASE=https://api.blablador.example.com/v1\n")

    # Write default models
    if default_models:
        lines.append(f'AISUITE_DEFAULT_MODELS="{default_models}"\n')
    elif get_config_value("AISUITE_DEFAULT_MODELS"):
        lines.append(f'AISUITE_DEFAULT_MODELS="{get_config_value("AISUITE_DEFAULT_MODELS")}"\n')
    else:
        lines.append("# AISUITE_DEFAULT_MODELS=meta-llama/Meta-Llama-3.1-8B-Instruct\n")

    # Write config
    CONFIG_FILE.write_text("".join(lines))


@app.command()
def setup(
    api_key: str | None = typer.Option(None, help="Blablador API key"),
    base_url: str | None = typer.Option(None, help="Blablador API base URL"),
    default_models: str | None = typer.Option(None, help="Default models (comma-separated)"),
    show: bool = typer.Option(False, help="Show current configuration"),
) -> None:
    """Configure hellmholtz CLI with persistent user-level settings."""
    if show:
        if CONFIG_FILE.exists():
            console.print(f"[bold]Current configuration ({CONFIG_FILE}):[/bold]")
            console.print(CONFIG_FILE.read_text())
        else:
            console.print("[yellow]No configuration found.[/yellow]")
        return

    write_config(api_key, base_url, default_models)

    if api_key:
        console.print("[green]✓ API key configured[/green]")
    if base_url:
        console.print("[green]✓ Base URL configured[/green]")
    if default_models:
        console.print("[green]✓ Default models configured[/green]")

    console.print(f"\n[green]Configuration saved to: {CONFIG_FILE}[/green]")
    console.print("\nThe configuration is now persistent across all projects!")
    console.print("\nRun 'hellm setup --show' to view your configuration.")
    console.print("Run 'hellm models' to verify it's working.")


def register_setup_commands(parent_app: typer.Typer) -> None:
    """Register setup commands with the main app."""
    parent_app.add_typer(app, name="setup", help="Setup and configuration commands")
